### ISSUE TITLE
'append' flag in appender config

### ISSUE THREAD

**Issue by stariy95** [bootique/bootique-logback#48]
`append` flag in SLF4J file appender can be useful in some cases, so we can support it. If set to `false` log file will be truncated. It should be true by default to keep backward compatibility.
```
log:
  level: debug
  appenders:
  - type: file
    logFormat: '%c{20}: %m%n'
    file: target/logs/file.log
    append: false
```
