### ISSUE TITLE
Logback "filters" in Bootique configurations

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-logback#50]
Let's shadow one more Logback configuration feature in Bootique - [filters](http://logback.qos.ch/manual/filters.html). This would allow to configure a set of appenders to split the log stream based on some criteria without resorting to XML. E.g.:

```yaml
log:
  logFormat: '%c{20}: %m%n'
  appenders:
    - type: file
      file: errors.txt
      filter:
         type: threshold
         level: WARN
    - type: file
      file: log.txt
      filter:
         type: threshold
         level: INFO
```
